Manual Gentoo Linux
===================
v1.0, 2013-04-09
:doctype:     book
:description: pentru arhitectura amd64 Instalarea Gentoo
:imagesdir: assets/images
:homepage: http://gentoo-land.org/

== Despre Instalarea Gentoo Linux.

=== Introducere

[role="indented"]
Bine ați venit!

[role="indented"]
În primul rând vă urăm, bun venit în lumea minunată Gentoo.  Sunteți
pe cale de a descoperi lumea flexibilității și performanței. Gentoo în
primul rând înseamnă flexibilitatea alegerii. Odată ce veți hotărî să
instalați Gentoo Linux, procedeul de instalare vă permite o foarte
mare flexibilitate în alegerea modalității de instalare, care poate fi
compilarea întregului sistem de la început sau doar instalând
binarele, aveți posibilitatea de a alege componentele de sistem cum
sunt bootloader-ul, logger-ele etc.

[role="indented"]
Gentoo este o metadistribuție modernă și foarte
rapidă, ce are o structură flexibilă. Gentoo este construit în jurul
conceptului free software și pune la dispoziția utilizatorilor toate
resursele. Portage, sistemul de administrare al pachetelor utilizat de
Gentoo, este scris în limbajul de programare Python, utilizatorii
având acces la codul sursă și putând modifica sursele în funcție de
necesitățile proprii. Sistemul de pachete Gentoo utilizează codul
sursă al programelor (deși oferă și suport pentru binare
precompilate), iar configurarea Gentoo se efectuează prin editarea
directă a fișierelor de configurare (fișiere de tip text, normale). Cu
alte cuvinte este un sistem deschis. Este foarte important să
înțelegeți că posibilitatea de a alege fac ca Gentoo sa
funcționeze. Noi nu vă forțăm în nimic din ceea ce vă displaceți. În
cazul în care credeți acest lucru, va rugăm să ne scrieți un
https://bugs.gentoo.org[bugreport].

Cum este structurat procesul de instalare?

* După pasul 1, vă aflați în mediul de lucru și sunteți pregătit
  pentru instalarea Gentoo

* După pasul 2, conexiunea la internet este pregătită pentru
  instalarea Gentoo

* După pasul 3, hard disk-ul este pregătit pentru a găzdui Gentoo

* După pasul 4, mediul de instalare este pregătit și puteți
  utiliza chroot pentru integrarea în noul mediu

* După pasul 5, pachetele de bază, ce sunt la fel pentru toate
  sistemele Gentoo, vor fi instalate

* După pasul 6, Kernel-ul Linux va fi compilat

* După pasul 7, vor fi completate majoritatea fișierelor de
  configurare Gentoo

* După pasul 8, utilitarele de sistem necesare(pe care le puteți
  alege dintr-o listă completă) sunt instalate

* După pasul 9, aplicația bootloader aleasă a fost instalată și
  configurată și sunteți log-ați în noua instalare Gentoo

* După pasul 10, noul dvs. mediu Gentoo, va fi gata de explorat

[role="indented"]
Gentoo Linux vă permite o foarte mare flexibilitate în alegere, pe
care vom încerca să le explicam atât din punct de vedere al punctelor
forte cât și al punctelor slabe. Vom continua cu un set de opțiuni
implicite, identificate cu "Implicite: " în titlu.  Celelalte opțiuni
sunt marcate cu "Alternativ: ". Să nu considerați că opțiunile
implicite sunt cele recomandate. În orice caz, sunt ceea ce credem că
cei mai mulți dintre utilizatori vor folosi.

În anumite cazuri puteți opta pentru soluții marcate ca "Opțional: ",
care nu sunt obligatorii în timpul instalării Gentoo. Aveți grijă la
anumite opțiuni care pot depinde de alte opțiuni ce au fost alese sau
ce vor depinde de anumiți pași ce vor fi executați în prealabil sau
după alegerea opțiunii și pe care îi vom menționa în documentația de
față.

Care sunt opțiunile?

Gentoo Poate fi instalat în diferite moduri. Aveți posibilitatea de a
descărca și instala Gentoo Linux de pe unul din mediile de instalare
CD disponibile, de pe un alt CD boot-abil (cum este Knoppix), boot-ând
din rețea, de pe o dischetă rescue etc.

Acest document acoperă modalitatea de instalare utilizând un mediu de
instalare CD Gentoo sau în unele cazuri bootarea din rețea. Această
modalitate de instalare presupune că doriți să instalați ultima
versiune a fiecărui pachet. Dacă doriți să efectuați o instalare fără
rețea, va trebui să consultați
http://www.gentoo.org/doc/en/handbook/[Manualele Gentoo] ce conțin
instrucțiunile de instalare pentru un mediu fără rețea.

Nota: Pentru o instalare de pe un alt CD decât cel oficial, incluzând
discuri optice non-Gentoo, va rugam sa citiți ghidul de instalare
alternativa.

Dacă doriți o instalare din rețea, ar trebui sa citiți
http://www.gentoo.org/doc/en/handbook/[Manualele Gentoo] , ce conțin
pașii de instalare dintr-o rețea.

De asemenea, notați faptul că dacă doriți să utilizați GRP (Gentoo
Reference Platform, o colecție de pachete precompilate destinate
utilizării imediate după o instalare Gentoo), trebuie să urmați
instrucțiunile din http://www.gentoo.org/doc/en/handbook/[Manualele
Gentoo].

Pentru instrucțiuni despre alte metode de instalare, vă rugăm să
consultați http://www.gentoo.org/doc/en/altinstall.xml[Ghidul de
Instalare Alternativă].  De asemenea, vă oferim un document cu
http://www.gentoo.org/doc/ro/gentoo-x86-tipsntricks.xml[Sfaturi și
Trucuri pentru Instalarea Gentoo] care vă poate fi de folos, de
asemenea. În cazul în care considerați că instrucțiunile de instalare
curente sunt prea elaborate, puteți utiliza Ghidul de Instalare Rapid,
disponibil pe pagina noastră de
http://www.gentoo.org/doc/en/index.xml?style=printable[Resurse de
Documentare], dacă arhitectura dumnevoastră dispune de un asemenea
document.

De asemenea aveți mai multe posibilități: puteți compila întregul
sistem de la bază sau a utiliza un mediu precompilat care permite o
instalare foarte rapidă. și desigur puteți utiliza metoda de instalare
intermediară unde nu este necesară compilarea întregului sistem ci
doar a unei părți din sistemul de bază care vine semi-precompilat.

Probleme?

Dacă ați găsit o eroare sau neconcordanță în procesul de instalare
(sau documentația de instalare) vă rugăm să vizitați
http://bugs.gentoo.org[sistemul de urmărire al bug-urilor] și
verificați dacă eroarea descoperită de către dumneavoastră este
cunoscută. Dacă nu a fost semnalată creați un bugraport pentru a
permite corectarea erorilor într-un timp cat mai scurt.  Nu vă temeți
de dezvoltatorii cărora le atribuiți bug-urile (semnalate de dvs) --
în general ei nu mănâncă oameni.

Notați că, deși documentul pe care îl citiți acum este specific
arhitecturii, va conține referințe și către alte arhitecturi, de
asemenea. Aceasta se întâmplă deoarece multe părți ale Manualului
Gentoo utilizează cod sursă ce este comun pentru toate arhitecturile
(pentru a evita multiplicarea eforturilor și irosirea resurselor de
dezvoltare). Vom încerca să minimizăm aceste informații pentru a evita
confuzia.

Dacă pe parcursul procesului de instalare întâmpinați greutăți și nu
sunteți sigur de natura problemei care poate fi problemă-utilizator
sau problemă-software și răspunsul nu-l puteți găsi în documentația de
față sunteți invitați să va alătura la canalul de discuții oficial
gentoo join #gentoo de pe irc.freenode.net unde cu siguranța veți
putea găsi răspuns la problemele și întrebările ce vă
interesează. Bineînțeles, sunteți binevenit și în alte situații

Dacă aveți întrebări referitoare la Gentoo, vizitați
http://www.gentoo.org/doc/ro/faq.xml[Întrebări frecvente despre Gentoo
Linux] , pe care le puteți găsi la
http://www.gentoo.org/doc/ro/[Documentații Gentoo]. De asemenea puteți
consulta http://www.gentoo.org/doc/ro/faq.xml[FAQs] de pe
http://forums.gentoo.org[forumuri].

Alegerea Mediului de Instalare Corect

=== Necesități Hardware

Introducere

Înainte de a începe, avem nevoie să cunoaștem componentele hardware ce
sunt suportate de Gentoo Linux pentru o instalare reușită.

[cols=2]
.Necesități Hardware
|===
|Procesor
|AMD64 sau ulterior

|Memorie
|256 MOcteți

|Spațiu pe disc
|2.5 GOcteți (excluzând spațiul swap)

|Spațiu swap
|Cel puțin 512 MOcteți
|===

Ar trebui să verificați
http://www.gentoo.org/proj/en/base/amd64/?style=printable[Gentoo
AMD64 Project Page] înainte să începeți.

=== Mediile Gentoo Installation CD

Mediile Gentoo Installation CD sunt boot-abile și conțin mediu Gentoo
complet funcțional. Acestea vă permit să boot-ați de pe CD. În timpul
procesului de boot-are, sistemul va încerca identificarea tuturor
componentelor hardware și instalarea driverelor specifice. Mentenanța
acestora este efectuată de către dezvoltatorii Gentoo.

Toate mediile Installation CD vă permit să boot-ați, să puteți
configura rețeaua, inițializa partiție și începe instalarea Gentoo de
pe Internet.

Mediul Gentoo Installation CD Minimal

Mediul Installation CD Minimal este denumit
install-amd64-minimal-<release>.iso și ocupă numai 200 MOcteți de
spațiu pe disc. Puteți utiliza acest mediu Installation CD pentru a
instala Gentoo, dar întotdeauna cu o conexiune la Internet activă.

[cols=2]
|===
|Mediul Installation CD Minimal
|Pro și Contra

|Plus
|Ușor de descărcat din cauza dimensiunilor reduse

|Minus
|Nu conține arhiva +stage3+, versiunea snapshot pentru Portage,
pachetele necesare pentru instalarea GRP, de aceea nu există
posibilitatea instalării fără conexiune la internet
|===

Mediul Gentoo Installer LiveDVD

Puteți utiliza acest mediu Installation DVD pentru a instala Gentoo,
și chiar pentru a instala Gentoo fără a avea o conexiune activă la
Internet, doar în cazul în care doriți să aduceți Gentoo pe un alt PC
decât cel pe care instalați Gentoo. La aproximativ fiecare 6 luni
Comunitatea Gentoo pune la dispoziție o imagine DVD a sistemului de
operare Gentoo ce poate fi instalata și ea pe hard
disk. Instrucțiunile de instalare pot fi puțin diferite deoarece acest
manual are ca scop instalarea de pe mediul Gentoo Instalation CD
Minimal. În orice caz puteți să ajungeți în contul root invocând sudo
su sau sudo -i în terminal.

[cols=2]
|===
|Mediul Installer LiveCD
|Pro și Contra

|Plus
|Conține toate pachetele necesare pentru o funcționare completă a
sistemului. Facilitează instalarea Gentoo Linux fără suport
pentru rețea.

|Minus
|Mult de descărcat
|===


Arhiva Tar Stage3

Un fișier +tar+ +stage3+ este o arhivă ce conține un mediul minimal
Gentoo, potrivit pentru a continua instalarea Gentoo utilizând
instrucțiunile din acest manual. Anterior, Manual Gentoo descria
instalarea utilizând una din cele 3 arhive +tar+ +stage+. În timp ce
Gentoo încă mai oferă arhivele +tar+ +stage1+ și +stage2+, modalitatea
de instalare oficială utilizează o arhivă +tar+ +stage3+. Dacă sunteți
interesat să utilizați un fișier +tar+ +stage1+ sau +stage2+, vă rugăm
să consultați documentul cu Întrebări Frecvente în Gentoo, secțiunea
http://www.gentoo.org/doc/en/faq.xml?style=printable#stage12[Cum
Instalez Gentoo Utilizând O Arhivă Tar Stage1 sau Stage2?]

Arhivele +stage3+ pot fi descărcate din directorul
+releases/amd64/autobuilds/current-stage3/+ de pe oricare din
http://www.gentoo.org/main/en/mirrors.xml?style=printable[Mirror-urile
Oficiale Gentoo] si nu sunt oferite pe mediul LiveCD.

=== Descărcarea, Scrierea și Bootarea unui Mediu Installation CD

Descărcarea și Scrierea Mediului Installation CD

Ați ales instalarea Gentoo utilizând un mediu Installation CD.  Vom
începe prin a descărca și a scrie mediul Installation CD ales. Am
tratat anterior mediile Installation CD disponibile, dar de unde le
putem descărca?

Puteți descărca unul din mediile Installation CD disponibile (și dacă
doriți, Packages CD, de asemenea) de pe unul din site-urile
mirror. Mediile Installation CD se găsesc în directorul
+releases/amd64/autobuilds/current-iso+.

În director veți găsi fișierele cu extensia ISO. Aceste fișiere sunt
imagini exacte ale CD-urilor originale și care pot fi scrise pe
DVD-R(W)/DVD+R(W), CD-R(W).

În caz că vă întrebați dacă fișierul descărcat este corupt sau nu, îi
puteți verifica suma de control SHA-2 oferită de noi (cum ar fi
install-amd64-minimal-<release>.iso.DIGESTS). Puteți verifica suma de
control SHA-2 utilizând utilitarul sha512sum pentru Linux/Unix, sau
File Checksum Tool pentru Windows.

O altă metodă de verificare a integrității imaginii LiveCD-ului
descărcat, este utilizarea GnuPG pentru verificarea semnăturii
criptografice ce v-o oferim (fișierul ce are terminația .asc).
Descărcați fișierul ce conține semnătura și obțineți cheia publică.

NOTE: Substitute the key ids with those mentioned on the release
engineering site)


[source,bash]
.Obținerea cheii publice
----
# gpg --keyserver subkeys.pgp.net --recv-keys 96D8BF6D 2D182910 17072058
----


[source,bash]
.Verificarea semnăturii criptografice
----
# gpg --verify <fișierul cu semnătura> <fișierul iso descărcat>
----


Pentru a scrie imaginile ISO pe CD-uri trebuie să selectați
raw-burning. Felul cum activați această opțiune este dependent foarte
mult de platformă. Vom trata aici cdrecord și K3B; pentru mai multe
informații consultați documentul despre
http://www.gentoo.org/doc/ro/faq.xml#isoburning[Întrebări Frecvente
despre Gentoo].

* Pentru cdrecord, trebuie doar să tastați cdrecord dev=/dev/sr0
  <fișierul iso descărcat> (înlocuiți /dev/sr0 cu calea către
  unitatea dvs. CD-RW)

* Pentru cdrecord, trebuie doar să tastați cdrecord dev=/dev/sr0
  <fișierul iso descărcat> (înlocuiți /dev/sr0 cu calea către
  unitatea dvs. CD-RW)

Boot-area Mediului Installation CD

IMPORTANT: Consultați cu atenție întreaga subsecțiune înainte de a
continua, pentru că, probabil nu veți mai avea această posibilitate
înainte de a continua ulterior.

După ce ați scris mediul Installation CD a venit timpul să
boot-ăm. Scoateți CD-ul (dacă este prezent) din unitatea CD-ROM,
reporniți PC-ul și intrați în BIOS. Această operație se poate efectua
apăsând una din tastele DEL, F1 sau ESC, depinzând de producătorul
BIOS-ului instalat. În meniul din BIOS schimbați ordinea boot-ării
unităților de disc, și anume setați CD-ROM-ul ca primul disc de pe
care să se înceapă citirea inițializării sistemului de operare. În
majoritatea cazurilor submeniul pentru schimbarea ordinii de boot se
poate găsi în meniul "CMOS Setup" Dacă nu activați opțiunea de boot de
pe CD-ROM după inițializarea BIOS-ului, PC-ul va încărca sistemul de
operare de pe hard-disc ignorând CD-ROM-ul.

Introduceți DVD/CD-ul în unitatea CD-ROM și reporniți PC-ul. După ce
CD-ul a inițiat procedura de boot va apărea un prompt de boot.
Apăsând tasta Enter procesul de boot a CD-ului va continua cu
opțiunile prestabilite pentru inițializarea sistemului, sau puteți
boot-a mediul Installation CD cu opțiuni suplimentare prin
specificarea unei imagini de kernel, urmată de opțiuni de boot și apoi
apăsarea Enter.

Specificarea Kernel-ului? Mediul Installation CD vă oferă mai multe
imagini de kernel. Kernel-ul implicit este gentoo. Alte imagini de
kernel sunt specifice unor anume necesități hardware și variantele
-nofb ce dezactivează opțiunea framebuffer.

În continuare veți regăsi o prezentare scurtă a imaginilor de kernel
disponibile:


[cols=2]
|===
|Kernel
|Descriere

|gentoo
|Kernel implicit cu suport pentru sisteme multiprocesor

|gentoo-nofb
|La fel ca și în cazul gentoo, dar fără suport pentru framebuffer

|memtest86
| Va încărca utilitarul pentru testarea memoriei RAM de erori
|===


Puteți utiliza și opțiuni de kernel. Ele reprezintă setări opționale
ce le puteți (dez)activa în funcție de necesități.  Lista de opțiuni
prezentată mai jos va apare la apăsarea tastei F2 în bootscreen.


[cols=2]
|===
|acpi=on
|Încarcă suportul pentru ACPI și de asemenea pornește daemon-ul la
boot când rulam de pe CD. Aveți nevoie de acesta doar dacă sistemul
dumneavoastră are nevoie de ACPI pentru a funcționa.  Acesta nu este
necesar pentru suportul Hyperthreading.

|acpi=off
|Dezactivează suportul ACPI. Acesta este necesar pentru hardware mai
vechi și este imperios necesar să folosim APM. Acest parametru
(opțiune) va dezactiva suportul Hyperthreading din procesorul
dumneavoastră.

|console=X
|Aceasta stabilește modul de accesare a CD-ului. Prima opțiune este
dispozitivul, cel mai frecvent ttyS0 pe arhitectura x86, urmat de
orice tip de conexiune, care sunt separate prin virgula.  Opțiunile
inițiale sunt 9600,8,n,1.

|dmraid=X
|Vă permite să trimiteți spre sistemul device-mapper RAID o
opțiune. Aceasta opțiune trebuie sa fie scrisă intre ghilimele.

|doapm
|Încarcă modulul APM. De asemenea este nevoie sa dezactivați acpi în
cazul în care folosiți aceasta opțiune.

|dopcmcia
|Pornește serviciul pcmcia pentru dispozitivele cdroms PCMCIA

|doscsi
|Încarcă suportul pentru controlere SCSI. De asemenea este necesar
pentru a putea boota majoritatea deviceurilor USB.

|sda=stroke
|Vă permite să partiționați întregul harddisk, chiar și atunci când
BIOS-ul nu poate manipula discuri mari.

|ide=nodma
|Forțează dezactivarea DMA pentru dispozitivele IDE cu probleme de
funcționare

|noapic
|Dezactivează apic (Advanced Programmable Interrupt Controller) acesta
fiind prezent în plăcile de bază noi. Este cunoscut faptul că poate
provoca probleme pe hardware vechi.

|nodetect
|Dezactivează întreaga autodetectare realizată de CD, inclusiv
autodetectarea și probarea DHCP. Această opțiune este bună în cazul în
care facem debugging în cazul unui driver cu probleme sau a unui CD.

|nodhcp
|Dezactivează DHCP pentru rețelele detectate. Este folositoare în
cazul rețelelor cu adresa ip statică.

|nodmraid
|Dezactivează suportul pentru RAID.

|nofirewire
|Dezactivează încărcarea modulelor Firewire. Este necesară în cazul în
care hardwareul Fireware vă creează probleme atunci când bootați de pe
CD.

|nogpm
|Dezactivează suportul pentru mouse în consola (tty).

|nohotplug
|Dezactivează încarcarea scripturilor de inițializare hotplug și
coldplug. Această opțiune este bună în cazul în care facem debugging
în cazul unui driver cu probleme sau a unui CD.

|nokeymap
|Dezactivează selecția definițiilor de taste pentru tastaturile cu
dispunere non-us.

|nolapic
|Dezactivează APIC din kernel.

|nosata
|Dezactivează încărcarea modulului disponibil pentru Serial ATA.  Este
folositoare atunci când avem probleme cu sistemul SATA.

|nosmp
|Dezactivează SMP, sau Symmetric Multiprocessing, pentru kernelurile
cu suport SMP.

|nosound
|Dezactivează suportul pentru sunet și setările pentru volum. Este
folositoare atunci când hardwareul pentru sunet cauzeaza probleme.

|nousb
|Dezactivează încărcarea modulului usb din initrd, dezactivează
hotplug.

|slowusb
|Adauga pauze mai lungi în procesul de bootare pentru unitati optice
pe usb (USB CDROMs).
|===


Acum boot-ați de pe CD, selectați un kernel (dacă nu sunteți mulțumit
de imaginea gentoo implicită) cu opțiunile dorite. În exemplul de mai
jos, vă prezentăm modalitatea de a boot-a imaginea de kernel gentoo cu
+dopcmcia+ ca parametri:


[source,bash]w
.Boot-area mediului Installation CD
----
# boot: gentoo dopcmcia
----


Apoi, veți observa imaginea de boot și bara de progres. Dacă instalați
Gentoo pe un sistem cu o tastatură non-US, apăsați imediat Alt+F1
pentru a comuta in modul informativ și urmați promptul. Dacă nu se
efectuează nici o selecție în 10 secunde, cea implicită (tastatura US)
va fi luată in considerare și procesul de boot va continua. Odată ce
procesul de boot a fost finalizat veți fi logat în mediul "Live" al
Gentoo Linux ca "root", modul super user. În consola curentă puteți
observa promptul root ("#") și puteți comuta între alte console
utilizând combinațiile de taste +Alt-F2+, +Alt-F3+ și +Alt-F4+. Pentru
a reveni la consola inițială utilizați combinația de taste +Alt-F1+.

Acum, continuați cu Configurarea Suplimentară pentru Componentele
Hardware.

Configurarea Suplimentară pentru Componentele Hardware

Mediul Gentoo Installation CD, în timp ce boot-ează, încearcă să
identifice automat toate componentele hardware din sistem și încarcă
modulele de kernel ce fac posibilă accesarea acestor resurse
hardware. Dar, sunt și cazuri când încărcarea automată nu este
efectuată pentru modulele necesare. În cazul în care autodetectarea
componentelor PCI a eșuat în cazul unor componente ale sistemului
dvs., vor trebui încărcate manual modulele de kernel necesare. În
următorul exemplu vom încerca încărcarea modulului 8139too (ce oferă
suport pentru un anumit tip de plăci de rețea):

[source,bash]
.Încărcarea modulelor de kernel
----
# modprobe 8139too
----

Dacă aveți nevoie de suport PCMCIA, va trebui să porniți
script-ul de inițializare pcmcia:

[source,bash]
.Pornirea script-ului de inițializare PCMCIA
----
# /etc/init.d/pcmcia start
----

Opțional: Optimizarea Performanțelor Hard-Disk-ului

Dacă sunteți un utilizator avansat, puteți optimiza performanța
hard-disk-ului, utilizând hdparm. În combinație cu opțiunile -tT
puteți testa performanțele hard discului (executați testul de mai
multe ori pentru a avea o imagine cât mai precisă a vitezei
HDD-ului).

[source,bash]
.Testarea peformanței discului
----
# hdparm -tT /dev/sda
----

Pentru optimizare, puteți utiliza oricare din exemplele de mai
jos (sau experimenta cu propriile optimizări) ce utilizează
+/dev/hda+ ca disc (substituiți cu discul dvs.):

Optimizarea performanței hard-disk-ului.

[source,bash]
.Activarea DMA:
----
# hdparm -d 1 /dev/hda
----

[source,bash]
.Opțiuni sigure de creștere a performaței:
----
# hdparm -d 1 -A 1 -m 16 -u 1 -a 64 /dev/hda
----

Opțional: Conturi de Utilizator

Dacă doriți să permiteți accesul utilizatorilor externi la mediul
de instalare Gentoo Linux, sau utilizați chat-ul irssi fără
drepturi de root (pentru un nivel mai ridicat al securității),
trebuie să creați utilizatori separați și este necesară
modificarea parolei de root.

Pentru a schimba parola root, rulați utilitarul passwd.

[source,bash]
.Schimbarea parolei de root
----
# passwd
  New password: (Enter your new password)
  Re-enter password: (Re-enter your password)
----

Pentru crearea unui nou cont de utilizator trebuie să introducem
denumirea contului și parola ce va fi asociată contului nou
creat. Pentru aceasta vom utiliza comenzile useradd și passwd. În
exemplu de mai jos vom crea un user numit "john".

[source,bash]
.Crearea unui cont de utilizator
----
# useradd -m -G users john
# passwd john
  New password: (Enter john's password)
  Re-enter password: (Re-enter john's password)
----

Puteți efectua login în noul cont creat din root, utilizând comanda
su:

[source,bash]
.Comutarea la alt utilizator
----
# su - john
----

Opțional: Vizualizarea Documentației în Timpul Instalării

Dacă doriți consultarea documentației de pe CD, puteți rula imediat
aplicația links ce vă permite vizualizarea documentației:

[source,bash]
.Vizualizarea documentației de pe CD
----
# links /mnt/cdrom/docs/html/index.html
----

Totuși, este recomandat să utilizați Manualul Gentoo aflat online,
deoarece este mult mai recent decât cel oferit pe CD.  Puteți utiliza,
de asemenea, aplicația links, dar numai după ce ați terminat capitolul
despre Configurarea Rețelei (în caz contrar nu veți putea accesa
internetul pentru a putea consulta online Manualul Gentoo).

[source,bash]
.Accesarea Documentației Online
----
# links http://www.gentoo.org/doc/en/handbook/handbook-amd64.xml
----

Puteți reveni la terminalul inițial apăsând combinația de taste
+Alt-F1+.

Opțional: Pornirea Serviciului SSH

Dacă vreți ca alți utilizatori să poată accesa procesul de instalare
Gentoo Linux (posibil, ca să vă ajute să instalați Gentoo, sau chiar
să îl instaleze pentru dvs.), va trebui să le creați conturi de
utilizator sau chiar sa le oferiți parola de root (doar dacă aveți
încredere deplină în acel utilizator).

Pentru a inițializa serviciul SSH, executați comanda de mai jos:

[source,bash]
.Pornirea serviciului SSH
----
# /etc/init.d/sshd start
----

Pentru a putea utiliza serviciul ssh trebuie configurat accesul la
rețea. Continuați cu capitolul despre Configurarea Rețelei.

Configurarea rețelei

=== Detectarea Automată a Rețelei

Poate funcționa pur și simplu?

Dacă sistemul dumneavoastră este conectat la o rețea deservită de un
server DHCP, este foarte probabil ca suportul de rețea să fie deja
configurat automat. Dacă este așa, puteți beneficia de avantajul
comenzilor incluse pe mediul Installation CD cum ar fi ssh, scp, ping,
irssi, wget și links, alături de altele.

Dacă rețeaua a fost configurată automat, comanda /sbin/ifconfig ar
trebui să afișeze informații despre alte câteva interfețe în afara lo,
cum ar fi eth0:

[source,bash]
----
# /sbin/ifconfig
 eth0  Link encap:Ethernet HWaddr 00:50:BA:8F:61:7A
       inet addr:192.168.0.2 Bcast:192.168.0.255 Mask:255.255.255.0
       inet6 addr: fe80::50:ba8f:617a/10 Scope:Link
       UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
       RX packets:1498792 errors:0 dropped:0 overruns:0 frame:0
       TX packets:1284980 errors:0 dropped:0 overruns:0 carrier:0
       collisions:1984 txqueuelen:100
       RX bytes:485691215 (463.1 Mb) TX bytes:123951388 (118.2 Mb)
       Interrupt:11 Base address:0xe800
----

Opțional: Configurare Proxy

Dacă aveți acces la Internet prin intermediul unui proxy, va trebui să
setați informațiile necesare în timpul instalării. Este foarte ușor să
specificați folosirea unui proxy: trebuie doar să definiți o variabilă
ce conține informațiile despre serverul folosit.

În majoritatea cazurilor, este suficient să definiți variabilele
folosind adresa serverului proxy. Ca exemplu, vom presupune că aceasta
este proxy.gentoo.org și portul este 8080.

Definirea serverelor proxy

....
(Pentru traficul HTTP)  # export http_proxy="http://proxy.gentoo.org:8080"
(Pentru traficul FTP)   # export ftp_proxy="ftp://proxy.gentoo.org:8080"
(Pentru traficul RSYNC) # export RSYNC_PROXY="proxy.gentoo.org:8080"
....

Dacă serverul proxy folosit necesită autentificare cu nume și parolă,
trebuie să folosiți următoarea sintaxă pentru definirea variabilelor:

....
Adăugarea nume/parolă la variabilele ce definesc proxy

http://username:password@server
....

În funcție de mediul de pe care ați ales să instalați Gentoo puteți
continua sau nu fără rețea (și acces Internet).

În general aveți nevoie de a configura rețeaua (și accesul la
Internet). Totuși, Gentoo vă permite și instalarea fără o conexiune la
Internet, acest lucru fiind posibil numai cu ajutorul LiveCD-urilor
Gentoo Universal.

De ce am nevoie de rețea?

Instalând Gentoo de pe Internet veți avea toate actualizările la
zi. Veți avea o instalarea bazată pe cel mai recent Portage (care este
o colecție de pachete furnizate împreună cu instrumentele necesare
administrării lor). Acesta este de altfel motivul pentru care
instalarea de pe Internet este preferată. Totuși, unele persoane nu
pot sau nu vor să instaleze Gentoo pe un sistem conectat la Internet.

Dacă sunteți în această situație atunci sunteți nevoiți să folosiți
LiveCD-urile Gentoo Universal. Acest LiveCD include cod sursă, o
versiune completă a Portage și instrumentele necesare instalării unui
sistem de bază Gentoo, și chiar mai mult. Această metodă are însă
prețul ei: nu veți avea ultimele versiuni ale programelor instalate,
deși diferențele vor fi minime.

Dacă vreți să urmați instalarea fără a fi conectați la internet și
doriți să folosiți un CD Universal Gentoo LiveCD, săriți peste restul
acestui capitol și continuați cu Pregătirea Discurilor.  Altfel,
continuați cu secțiunile despre configurarea suportului de rețea ce
urmează.

Testarea rețelei

Ați putea încerca să dați ping în serverele de nume ale provider-ului
dumneavoastră (cele scrise în /etc/resolv.conf) și apoi într-un site
la alegere, doar pentru a vă asigura că pachetele dumneavoastră ajung
pe internet și rezolvarea numelor funcționează corect, etc.

[source,bash]
.Exemplu de testare a rețelei
----
$ ping -c 3 www.yahoo.com
----

Dacă puteți utiliza, acum, rețeaua, puteți sări peste restul acestei
secțiuni și continua cu Pregătirea Discurilor. Dacă nu, citiți mai
departe.

=== Configurarea Automată a Rețelei

Dacă rețeaua nu funcționează imediat, unele medii de instalare vă
permit să folosiți net-setup (pentru rețele obișnuite sau wireless)
sau adsl-setup (pentru conexiuni ADSL) sau pptp (pentru conexiuni PPTP
- disponibilă doar pe arhitectura x86).

Dacă suportul dumneavoastră de instalare nu conține nici un astfel de
instrument sau rețeaua nu funcționează încă, continuați cu
Configurarea Manuală a Rețelei.

* Pentru conexiuni obișnuite continuați cu Implicit: Folosirea
  net-setup

* Pentru conexiuni ADSL continuați cu Alternativ: Folosirea
  RP-PPPoE

* Pentru conexiuni PPTP continuați cu Alternativ: Folosirea PPTP

  Implicit: Folosirea net-setup

Cea mai simplă cale de a configura rețeaua dacă aceasta nu s-a
efectuat în mod automat este să rulați scriptul net-setup:
